### PR TITLE
Fixed Laplace method 

### PR DESCRIPTION
**Pull request by cunchem**
* Corrected mistake in the formula (https://en.wikipedia.org/wiki/Laplace_distribution)
* Now uniform 2 uniform variables instead of 1

### CODE REVIEW

**Comment by ealdent** [comment]
Perhaps I'm misunderstanding the distribution, but the formula in that article is a function of one random variable (quoting):

```
Given a random variable U drawn from the uniform distribution in the interval (−1/2, 1/2], the random variable

X=\mu - b\,\sgn(U)\,\ln(1 - 2|U|)
has a Laplace distribution with parameters μ and b. 
```  

It looks like it could be calculated as the difference of two exponentials, so

`exponential(mean) - exponential(mean)` 

might be an alternative implementation.

**Comment by cunchem** [comment]
The definition of Wikipedia is a bit ambiguous. The U designates a uniform random distribution and not a single random variable. The first random variable should be used to draw the sign, while the second should be used for the "amplitude". Using the same variable realisation for both would mean that the sign and the amplitude are correlated. 

Now regarding the formula, the current version provides an erroneous distribution. Using a mean of 0, I get a distribution centered around 0.7. 
```
require "simple-random"
require 'descriptive_statistics'
sr = SimpleRandom.new
Array.new(100000){sr.laplace(0,1)}.mean
=> 0.6910468086276775
```
The proposed patch gives a distribution centered around 0.

**Comment by ealdent** [comment]
Ok, that makes sense.  Thanks for clarifying and fixing it.  Merging the pull request and I'll bump the gem when I get a chance later today.

**Comment by cunchem** [comment]
You're welcome. Thanks for library ;)

**Pull request merged**
